[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
lib_deps = 
    olikraus/U8g2@^2.35.0
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    claws/BH1750@^1.3.0

